apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
- ../base

images:
- name: IMAGE_TAG
  newName: gcr.io/google-samples/kubernetes-bootcamp
  newTag: v1

patchesStrategicMerge:
- hpa.yaml

configMapGenerator:
  - name: lab-props
    env: app.properties

secretGenerator:
  - name: lab-secret
    type: Opaque
    envs:
      - .secrets

