apiVersion: v1
kind: Service
metadata:
  labels:
    app: kubernetes-bootcamp
  name: kubernetes-bootcamp
  namespace: default
spec:
  ports:
  - nodePort: 30014
    port: 8080
  selector:
    app: kubernetes-bootcamp
  type: NodePort
