apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

resources:
- ../../base
- namespace.yaml

images:
- name: IMAGE_TAG
  newName: gcr.io/google-samples/kubernetes-bootcamp
  newTag: v1

patches:
- path: hpa.yaml

configMapGenerator:
  - name: lab-props
    env: app.properties

secretGenerator:
  - name: lab-secret
    type: Opaque
    envs:
      - .secrets

